### ISSUE TITLE
Metadata to Mollie

### ISSUE THREAD

**Issue by reyostallenberg** [axelvnk/SyliusMolliePayumBundle#4]
On https://github.com/axelvnk/SyliusMolliePayumBundle/blob/master/Payum/Action/CaptureAction.php#L55 only the transaction_id is added. Is it an idea to add at least also the ordernumber. Maybe use an event dispatcher to let developers at what they want?

**Comment by axelvnk** [comment]
You mean here https://github.com/axelvnk/SyliusMolliePayumBundle/blob/master/Payum/Api.php#L47 ? Because the line you're referring to is just what goes in the sylius database after the call has been made to Mollie. 

I guess we could do something like that, but adding the eventdispatcher seems a bit overkill to me. I've made every class overridable so if people need major customization, they can with little effort. Besides if they are adding more to the metadata, they also need to capture it on return and do something with it, so they need to start overriding anyways...

I'm pro to adding more than just the payment_id to the meta data.
